<a href="https://colab.research.google.com/github/yvrjsharma/LexInterviewsX/blob/main/Understanding_text_generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q transformers datasets

     |████████████████████████████████| 4.0 MB 8.2 MB/s 
     |████████████████████████████████| 325 kB 52.8 MB/s 
     |████████████████████████████████| 895 kB 50.6 MB/s 
     |████████████████████████████████| 6.6 MB 52.2 MB/s 
     |████████████████████████████████| 596 kB 49.4 MB/s 
     |████████████████████████████████| 77 kB 6.0 MB/s 
     |████████████████████████████████| 1.1 MB 49.4 MB/s 
     |████████████████████████████████| 136 kB 54.3 MB/s 
     |████████████████████████████████| 212 kB 61.6 MB/s 
     |████████████████████████████████| 127 kB 59.9 MB/s 
     |████████████████████████████████| 144 kB 53.7 MB/s 
     |████████████████████████████████| 94 kB 3.2 MB/s 
     |████████████████████████████████| 271 kB 51.9 MB/s 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which i

- Loading the 1.5 billion paramter version of GPT-2

### Greedy Decoding

In [ ]:
import torch 
from transformers import AutoTokenizer, AutoModelForCausalLM

In [ ]:
device = 'cuda'
model_name = "gpt2-xl"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name).to(device)

Downloading:   0%|          | 0.00/689 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/0.99M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.29M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/5.99G [00:00<?, ?B/s]

In [ ]:
import pandas as pd
input_txt = 'Transformers are the'
input_ids = tokenizer(input_txt, return_tensors='pt')["input_ids"].to(device)
iterations =[]
n_steps = 8
choices_per_step = 5

In [ ]:
input_ids

tensor([[41762,   364,   389,   262]], device='cuda:0')

In [ ]:
with torch.no_grad():
  for _ in range(n_steps):
    iteration = dict()
    iteration["Input"] = tokenizer.decode(input_ids[0])
    output = model(input_ids = input_ids)

    #apply softmax on logits
    next_token_logits = output.logits[0,-1,:]
    next_token_probs = torch.softmax(next_token_logits, dim=-1)
    sorted_ids = torch.argsort(next_token_probs, dim=-1, descending=True)
    #get highest probabilities
    for choice_idx in range(choices_per_step):
      token_id = sorted_ids[choice_idx]
      token_prob = next_token_probs[token_id].cpu().numpy()
      token_choice = (f"{tokenizer.decode(token_id)} ({100*token_prob:.2f}%)")
      iteration[f"Choice {choice_idx+1}"] = token_choice
    #append predicted token to input
    input_ids = torch.cat([input_ids, sorted_ids[None, 0, None]], dim=-1)
    iterations.append(iteration)

pd.DataFrame(iterations)

Input           Choice 1  \
0                               Transformers are the       most (8.53%)   
1                          Transformers are the most   popular (16.78%)   
2                  Transformers are the most popular       toy (10.63%)   
3              Transformers are the most popular toy      line (34.38%)   
4         Transformers are the most popular toy line        in (46.28%)   
5      Transformers are the most popular toy line in       the (65.99%)   
6  Transformers are the most popular toy line in the     world (69.26%)   
7  Transformers are the most popular toy line in ...         , (39.73%)   

            Choice 2               Choice 3               Choice 4  \
0       only (4.96%)           best (4.65%)   Transformers (4.37%)   
1   powerful (5.37%)         common (4.96%)         famous (3.72%)   
2       toys (7.23%)   Transformers (6.60%)             of (5.46%)   
3        in (18.20%)            of (11.71%)          brand (6.10%)   
4        of (15.09%)              , (4.94%)             on (4.40%)   
5   history (12.42%)        America (6.91%)          Japan (2.44%)   
6     United (4.55%)        history (4.29%)             US (4.23%)   
7         . (30.64%)            and (9.87%)           with (2.32%)   

              Choice 5  
0     ultimate (2.16%)  
1   successful (3.20%)  
2          and (3.76%)  
3         line (2.69%)  
4         ever (2.72%)  
5        North (1.40%)  
6            U (2.30%)  
7        today (1.74%)

In [ ]:
tokenizer.decode(input_ids[0]), model(input_ids=input_ids).logits[0,-1,:], torch.argsort(torch.softmax(model(input_ids=input_ids).logits[0,-1,:], dim=-1), dim=-1, descending=True)

('Transformers are the most popular toy line in the world,',
 tensor([-0.0776, -0.9037, -0.5826,  ..., -7.1016, -5.1974, -0.5922],
        device='cuda:0', grad_fn=<SliceBackward0>),
 tensor([  290,   351,   475,  ..., 39820,   191,   218], device='cuda:0'))

In [ ]:
#putting everything together
input_ids = tokenizer(input_txt, return_tensors='pt')["input_ids"].to(device)
output = model.generate(input_ids, max_new_tokens=n_steps, do_sample=False)
print(tokenizer.decode(output[0]))

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


Transformers are the most popular toy line in the world,


In [ ]:
#generating much longer text
max_length= 128
input_txt = """In a shocking finding, scientist discovered \
a herd of unicorns living in a remote, previously unexplored \
valley, in the Andes Mountains. Even more surprising to the \
researchers was the fact that the unicorns spoke perfect English.\n\n
"""
input_ids = tokenizer(input_txt, return_tensors='pt')["input_ids"].to(device)
output_greedy = model.generate(input_ids, max_length=max_length, do_sample=False)
print(tokenizer.decode(output_greedy[0]))

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In a shocking finding, scientist discovered a herd of unicorns living in a remote, previously unexplored valley, in the Andes Mountains. Even more surprising to the researchers was the fact that the unicorns spoke perfect English.


The researchers, from the University of California, Davis, and the University of Colorado, Boulder, were conducting a study on the Andean cloud forest, which is home to the rare species of cloud forest trees.


The researchers were surprised to find that the unicorns were able to communicate with each other, and even with humans.


The researchers were surprised to find that the unicorns were able


### Beam Decoding

In [ ]:
import torch.nn.functional as F

def log_probs_from_logits(logits, labels):
    logp = F.log_softmax(logits, dim=-1)
    logp_label = torch.gather(logp, 2, labels.unsqueeze(2)).squeeze(-1)
    return logp_label

In [ ]:
def sequence_logprob(model, labels, input_len=0):
    with torch.no_grad():
        output = model(labels)
        log_probs = log_probs_from_logits(
            output.logits[:, :-1, :], labels[:, 1:])
        seq_log_prob = torch.sum(log_probs[:, input_len:])
    return seq_log_prob.cpu().numpy()

In [ ]:
logp = sequence_logprob(model, output_greedy, input_len=len(input_ids[0]))
print(tokenizer.decode(output_greedy[0]))
print(f"\nlog-prob: {logp:.2f}")

In a shocking finding, scientist discovered a herd of unicorns living in a remote, previously unexplored valley, in the Andes Mountains. Even more surprising to the researchers was the fact that the unicorns spoke perfect English.


The researchers, from the University of California, Davis, and the University of Colorado, Boulder, were conducting a study on the Andean cloud forest, which is home to the rare species of cloud forest trees.


The researchers were surprised to find that the unicorns were able to communicate with each other, and even with humans.


The researchers were surprised to find that the unicorns were able

log-prob: -87.43


In [ ]:
#make it less repetitive
output_beam = model.generate(input_ids, max_length=max_length, num_beams=5, do_sample=False, no_repeat_ngram_size=2)
logp = sequence_logprob(model,output_beam, input_len=len(input_ids[0]))
print(tokenizer.decode(output_greedy[0]))
print(f"\nlog-prob: {logp:.2f}")

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In a shocking finding, scientist discovered a herd of unicorns living in a remote, previously unexplored valley, in the Andes Mountains. Even more surprising to the researchers was the fact that the unicorns spoke perfect English.


The researchers, from the University of California, Davis, and the University of Colorado, Boulder, were conducting a study on the Andean cloud forest, which is home to the rare species of cloud forest trees.


The researchers were surprised to find that the unicorns were able to communicate with each other, and even with humans.


The researchers were surprised to find that the unicorns were able

log-prob: -93.12


In [ ]:
#High Temperature and Sampling
output_temp = model.generate(input_ids, max_length = max_length, do_sample=True, temperature=2.0, top_k=0)
print(tokenizer.decode(output_temp[0]))

#cooling down the temp
output_temp = model.generate(input_ids, max_length = max_length, do_sample=True, temperature=0.5, top_k=0)
print(tokenizer.decode(output_temp[0]))

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In a shocking finding, scientist discovered a herd of unicorns living in a remote, previously unexplored valley, in the Andes Mountains. Even more surprising to the researchers was the fact that the unicorns spoke perfect English.


Russ Guerrero,thropope Apheader hit hide pricingety layerBen Est driven08 leptinResearch near'sinstcription in Hueoranposition group twistedron160tons Murill
 BronzeFivechen metriczan Bill climbingpeace tourismTem SkyHubpert Hideproclaimed massesuccl assumptions occultService slated strip 189 Younglbs Active ArkansasSpecificThirty micHighvertsipe JalosaHmiiteubidentlearpod Dentomen electronCole
In a shocking finding, scientist discovered a herd of unicorns living in a remote, previously unexplored valley, in the Andes Mountains. Even more surprising to the researchers was the fact that the unicorns spoke perfect English.


The scientists were surprised to find the unicorns in the valley, located in the Andes Mountains, about 1,300 miles from the nearest cit

In [ ]:
#Sampling with top k
input_ids = tokenizer(input_txt, return_tensors='pt')["input_ids"].to(device)
input_txt, input_ids

output_topk = model.generate(input_ids, max_length=max_length, do_sample=True, top_k =50)

print(tokenizer.decode(output_topk[0]))

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In a shocking finding, scientist discovered a herd of unicorns living in a remote, previously unexplored valley, in the Andes Mountains. Even more surprising to the researchers was the fact that the unicorns spoke perfect English.


The researchers, led by Dr. Robert Dudley, have been studying the creatures in remote mountain areas of western Argentina on several occasions since 2007. They say, they have been monitoring every unicorn they visit as well as some that have been killed over the years. The study was published in Biology Letters.


Their findings indicated that unicorns do indeed live in the mountains, as they have been observed crossing the


In [ ]:
#sampling with nucleus

output_topk = model.generate(input_ids, max_length=max_length, do_sample=True, top_p =0.90)

print(tokenizer.decode(output_topk[0]))

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In a shocking finding, scientist discovered a herd of unicorns living in a remote, previously unexplored valley, in the Andes Mountains. Even more surprising to the researchers was the fact that the unicorns spoke perfect English.


The scientists, from the University of Illinois, used infrared cameras and microphones to record their interactions with each other and with the ground.


The team also collected hair and saliva samples from the animals to analyze them. The study is part of a larger study of animal vocalizations in the Andes, led by the University of Iowa.


The researchers said that the animals could be a form of human
